# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
researchgate_icon: /assets/google-scholar.svg

# Content configuration version
version: 2

# Personal info
name: Hossein Tavakolian
title: Associate Professor, Allameh Tabataba'i University
website: https://aris.atu.ac.ir/en/hossein.tavakolian
email: hossein.tavakolian@atu.ac.ir

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: hosstavakolian
github_username:  tavakolianh
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: hosstav
linkedin_username: hossein-tavakolian-698514138
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0002-7513-6282


# Additional icon links
additional_links:
#- title: itsgoingto.be
 # icon: fas fa-globe
 # url: https://aris.atu.ac.ir/cv/researcher_En.php
- title: orcid1.be
  icon: fab fa-orcid
  url: https://orcid.org/0000-0002-7513-6282?lang=en
- title: researchgate1.be
  icon: fab fa-researchgate
  url: https://www.researchgate.net/profile/Hossein-Tavakolian-2
- title: googlescholar1.be
  icon: fab fa-google
  url: https://scholar.google.com/citations?user=NgTrhd0AAAAJ&hl=en
  
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Hossein Tavakolian and I'm associate professor of [Allameh Tabataba'i University](https://atu.ac.ir/en). 

  My primary research pursuits encompass Dynamic Stochastic General Equilibrium (DSGE) Models, Monetary Economics, and Data Analysis. My current research efforts are centered around investigating the intricacies of uncertainty and stochastic states within DSGE models.
  
  I am most skilled in: <mark>Dynare</mark>, <mark>MATLAB</mark> and <mark>Python</mark>
  
  You can download my CV [here](pdfs/CV.pdf)



content:
  - title: Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Published Papers
        #caption: 2010 - 2013
        #sub_title: In English
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          <span style="font-size: 16px;">1. Arbabafzali, M. , Nadri, K., & Tavakolian, H. (2023). Can the transition from Basel II to III change the monetary policy impact on the Iranian economy and banking system?. Economic Analysis and Policy, 77, 357-371.[https://doi.org/10.1016/j.eap.2022.11.018](https://doi.org/10.1016/j.eap.2022.11.018)</span>
          
          <span style="font-size: 16px;">2. Ghiaie, H., Tabarraei, H. R., & Tavakolian, H. (2022). Alternative monetary policy regimes in an oil-exporting economy. The Quarterly Review of Economics and Finance, 83, 161-177.[https://doi.org/10.1016/j.qref.2021.11.003](https://doi.org/10.1016/j.qref.2021.11.003)</span>

          <span style="font-size: 16px;">3. Tavakolian, H., & Taherpoor, J. (2022). Fiscal and Monetary Policy Interaction in Iran: A TVP-VARMA Model. Iranian Economic Review, 26(3), 637-665.[https://doi.org/10.22059/ier.2022.89094](https://doi.org/10.22059/ier.2022.89094)</span>

          <span style="font-size: 16px;">4. Sadidi, M., Tavakolian, H., & Asim, M. (2021). Analysis of the formation of the price bubble in the financial market: with an emphasis on the price bubble in the insurance industry and the stock market with the Markov-switching approach. International Journal of Nonlinear Analysis and Applications, 12, 1-14.[https://doi.org/10.22075/ijnaa.2021.4758](https://doi.org/10.22075/ijnaa.2021.4758)</span>

          <span style="font-size: 16px;">5. Akbari, M., Loganathan, N., Tavakolian, H., Mardani, A., & Štreimikienė, D. (2021). The dynamic effect of micro-structural shocks on private investment behavior. Acta Montanistica Slovaca, 26(1), 1-17.[https://doi.org/10.46544/AMS.v26i1.01](https://doi.org/10.46544/AMS.v26i1.01)</span>

          <span style="font-size: 16px;">6. Ghasemi, A., Akbari Moghadam, B., & Tavakolian, H. (2020). A Study of the Financial Instability and Banking Intermediaries by Using a DSGE Modeling Approach. Iranian Economic Review, 24(4), 1025-1047.[https://doi.org/10.22059/ier.2020.78834](https://doi.org/10.22059/ier.2020.78834)</span>

          <span style="font-size: 16px;">7. Bastanzad, H., Davoudi, P., & Tavakolian, H. (2018). Foreign Exchange Rate Pricing at the Future Contract (Case of IR of Iran). Iranian Economic Review, 22(1), 253-293.[https://doi.org/10.22059/ier.2018.65364](https://doi.org/10.22059/ier.2018.65364)</span>

          <span style="font-size: 16px;">8. Abbasinejad, H., Tavakolian, H., & Husseini, S. K. (2018). The effects of monetary policy on output and inflation in Afghanistan: A dynamic stochastic general equilibrium approach. Iranian Economic Review, 22(2), 375-408.[https://doi.org/10.22059/ier.2018.66159](https://doi.org/10.22059/ier.2018.66159)</span>

          <span style="font-size: 16px;">9. Permeh, Z., Ghorbani, M., Tavakolian, H., & Shahnoshi, N. (2017). Effects of Oil Price Shocks on Agricultural Sector Using Dynamic Stochastic General Equilibrium Model. Journal of Agricultural Science and Technology, 19(6), 1211-1226.[http://dorl.net/dor/20.1001.1.16807073.2017.19.6.14.9](http://dorl.net/dor/20.1001.1.16807073.2017.19.6.14.9)</span>

          <span style="font-size: 16px;">10. Komijania, A., Khalili Araghi, S. M., Abasinejad, H., & Tavakolian, H. (2014). Time-Varying Monetary Policy Reaction Function: The Case of Iran. Iranian Economic Review, 18(2), 87-103.[https://doi.org/10.22059/ier.2014.53320](https://doi.org/10.22059/ier.2014.53320)</span>

          <span style="font-size: 16px;">11. Komijani, A., & Tavakolian, H. (2011). The composition of foreign reserves of the central banks of selected countries: Will the euro replace the dollar?. Eurasian Economic Review, 1, 143-156.[https://link.springer.com/article/10.14208/BF03353828](https://link.springer.com/article/10.14208/BF03353828)</span>

          <span style="font-size: 16px;">12. Mehrara, M., Maki, M., & Tavakolian, H. (2010). The relationship between oil revenues and economic growth, using threshold methods (the case of Iran). OPEC Energy Review, 34(1), 1-14.[https://doi.org/10.1111/j.1753-0237.2010.00172.x](https://doi.org/10.1111/j.1753-0237.2010.00172.x)</span>

      - layout: left
        title: Published Papers
        caption: In Persian
        #sub_title: In English
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          To see my published papers in Persian, you can see my [Persian CV](https://aris.atu.ac.ir/hossein.tavakolian).

      - layout: left
        title: Books
        #caption: 2010 - 2013
        #sub_title: In English
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          <span style="font-size: 16px;">1. Tavakolian, H., & Sarem, M. (2016). DSGE models in DYNARE (Modeling, Solution and Estimation for Iran). The Best Book Award in Monetary Economics and Banking, Central Bank of Iran, 2018. [http://pub.mbri.ac.ir/Pages/BookDetail.aspx?Item_Id=503&Edition_Id=428](http://pub.mbri.ac.ir/Pages/BookDetail.aspx?Item_Id=503&Edition_Id=428)</span>

          <span style="font-size: 16px;">2. Mohsen M., Sarem, M., & Tavakolian, H. (2010). Mathematical Economics (A Dynamic Approach). [http://pub.mbri.ac.ir/Pages/BookDetail.aspx?Item_Id=503&Edition_Id=428](http://pub.mbri.ac.ir/Pages/BookDetail.aspx?Item_Id=503&Edition_Id=428)</span>



  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Allameh Tabataba'i University
        link: https://www.emofid.com/
        # link_text: boringcompany.com
        sub_title: Full Time
        caption: June 2021- Present
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
             <span style="font-size: 25px;">.</span><span style="font-size: 20px;"> Associate Professor.</span>

             <span style="font-size: 25px;">.</span><span style="font-size: 20px;"> Director of Commercial Economics, 2020-2022 .</span>

      - layout: left
        title: Mofid Securities
        link: https://www.emofid.com/
        # link_text: boringcompany.com
        sub_title: Prt Time
        caption: December 2014 - Present
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
             <span style="font-size: 25px;">.</span><span style="font-size: 20px;">	Director of Macroeconomic Analysis Department.</span>

      - layout: left
        title: Tehran Securities Exchange
        link: https://www.tse.ir/
        # link_text: boringcompany.com
        sub_title: Full Time
        caption: December 2014 - Present
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
             <span style="font-size: 25px;">.</span><span style="font-size: 20px;">	Economic Advisor.</span>


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          <span style="font-size: 16px;">1. Arbabafzali, M., Nadri, K., Tavakolian, H. (2023). Can the transition from Basel II to III change the monetary policy impact on the Iranian economy and banking system? Economic Analysis and Policy, 77, 357-371</span>

          <span style="font-size: 16px;">2. Afzali, M. A., Nadri, K., & Tavakolian, H. (2023). Can the transition from Basel II to III change the monetary policy impact on the Iranian economy and banking system?. Economic Analysis and Policy, 77, 357-371.[https://doi.org/10.1016/j.eap.2022.11.018](https://doi.org/10.1016/j.eap.2022.11.018)</span>


  - title: Teaching # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Fall Semester
        caption: 2023-24
        #sub_title: In English
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          <span style="font-size: 18px;">1. Advanced Macroeconomics, MA.</span>
          
          <span style="font-size: 14px;">Class Files: [Session1](pdfs/MacroMA4012.pdf), [Session2](pdfs/MacroMA4012.pdf)</span>
  
          <span style="font-size: 18px;">1. Monetary Economics, MA.</span>
          
          <span style="font-size: 14px;">Class Files: [Session1](pdfs/MacroMA4012.pdf), [Session2](pdfs/MacroMA4012.pdf)</span>

         





  - title: Teaching
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
      - Arbabafzali, M., Nadri, K., Tavakolian, H. (2023). Can the transition from Basel II to III change the monetary policy impact on the Iranian economy and banking system? Economic Analysis and Policy, 77, 357-371
      - Afzali, M. A., Nadri, K., & Tavakolian, H. (2023). Can the transition from Basel II to III change the monetary policy impact on the Iranian economy and banking system?. Economic Analysis and Policy, 77, 357-371.[DOI](https://doi.org/10.1016/j.eap.2022.11.018)


      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
